### ISSUE TITLE
Is the grad-cam suitable for PointNet++ architecture?

### ISSUE THREAD

**Issue by Hao-HUST** [Fragjacker/Pointcloud-grad-CAM#7]
Hi, 

In PointNet,  you take the feature vector before feeding it to the max-polling layer to produce the grad-cam result. (Correct me if I am wrong). For PointNet++, it is inevitable to import max polling to get the final feature vector. Such the max-pooling layers are harmful to getting grad-cam or do you have any suggestions about producing a grad-cam results from PointNet++?

**Comment by Fragjacker** [comment]
Greetings!

I am not familiar with the model architecture of PointNet++ so I can only make and educated guess. The whole reason the feature vector is pulled right before the max-pooling is to have the maximum of information retrieved from the network. The max-pooling layer inevitably removes information and changes the dimension of the matrix, making it unsuitable for retrieving the gradients.

My suggestions would be to try retrieving the feature vector from your network before any max-pooling has happened and feed that into p-grad-CAM. If that is not applicable then the whole grad-CAM approach may not be applicable.

**Comment by Hao-HUST** [comment]
Thanks for your replying. I will try to do some experiments based on your advice, and I will update it if I find something.

Close the issue now.
